In [1]:
import pandas as pd
import pyarrow
import openpyxl
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_dirty.csv"
               ,sep=","
               )

In [22]:
df.head(10)

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,NaN,ERR,3.1,7.0,NaN,2.0,5.000000,Facebook,10.0
1,U002,30.0,Other,5.1,7.0,8.0,5.0,3.000000,LinkedIn,10.0
2,U003,23.0,ERR,7.4,6.0,NaN,1.0,5.622212,YouTube,6.0
3,U004,36.0,Female,5.7,7.0,8.0,1.0,1.000000,TikTok,8.0
4,U005,34.0,Female,7.0,4.0,7.0,5.0,1.000000,X (Twitter),8.0
5,U006,38.0,Male,6.6,5.0,7.0,4.0,3.000000,LinkedIn,8.0
6,U007,26.0,Female,7.8,4.0,8.0,2.0,0.000000,TikTok,7.0
7,U008,26.0,Female,7.4,5.0,6.0,1.0,4.000000,Instagram,7.0
8,U009,39.0,Male,4.7,7.0,7.0,6.0,1.000000,YouTube,9.0
9,U010,NaN,ERR,6.6,6.0,8.0,0.0,2.000000,Facebook,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    500 non-null    object
 1   Age                        482 non-null    float64
 2   Gender                     500 non-null    object
 3   Daily_Screen_Time(hrs)     486 non-null    float64
 4   Sleep_Quality(1-10)        490 non-null    float64
 5   Stress_Level(1-10)         477 non-null    float64
 6   Days_Without_Social_Media  483 non-null    float64
 7   Exercise_Frequency(week)   484 non-null    float64
 8   Social_Media_Platform      500 non-null    object
 9   Happiness_Index(1-10)      473 non-null    float64
dtypes: float64(7), object(3)
memory usage: 39.2+ KB

In [5]:
df.describe()

,Age,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Happiness_Index(1-10)
count,482.000000,486.000000,490.000000,477.000000,483.000000,484.000000,473.000000
mean,37.222146,6.138320,6.895598,7.363026,3.549599,2.706973,9.202009
std,22.510519,3.454650,3.907355,4.019927,2.579419,1.900980,4.680201
min,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,4.000000
25%,25.000000,4.300000,5.000000,6.000000,2.000000,1.000000,7.000000
50%,35.000000,5.700000,6.000000,7.000000,3.000000,2.000000,9.000000
75%,43.000000,6.900000,7.000000,8.000000,5.000000,4.000000,10.000000
max,180.626294,29.345107,33.352217,33.533704,15.545850,11.946164,41.477006

In [3]:
df.drop_duplicates(keep="first",inplace=True)
df

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,NaN,ERR,3.1,7.0,NaN,2.0,5.000000,Facebook,10.0
1,U002,30.0,Other,5.1,7.0,8.0,5.0,3.000000,LinkedIn,10.0
2,U003,23.0,ERR,7.4,6.0,NaN,1.0,5.622212,YouTube,6.0
3,U004,36.0,Female,5.7,7.0,8.0,1.0,1.000000,TikTok,8.0
4,U005,34.0,Female,7.0,4.0,7.0,5.0,1.000000,X (Twitter),8.0
...,...,...,...,...,...,...,...,...,...,...
495,ERR,23.0,ERR,6.9,5.0,7.0,4.0,2.000000,ERR,10.0
496,U497,43.0,Female,5.6,7.0,6.0,5.0,2.000000,Facebook,9.0
497,U498,41.0,Male,7.7,5.0,NaN,2.0,5.265107,ERR,8.0
498,U499,23.0,Male,4.2,9.0,7.0,0.0,2.000000,Facebook,9.0
499,U500,43.0,Female,5.9,5.0,8.0,3.0,3.000000,X (Twitter),7.0

In [8]:
df['Gender'].value_counts()

Gender
Male      236
Female    217
ERR        25
Other      22
Name: count, dtype: int64

In [9]:
df['Sleep_Quality(1-10)'].value_counts()

Sleep_Quality(1-10)
6.000000     113
7.000000     110
5.000000      88
8.000000      64
4.000000      51
9.000000      32
3.000000       9
10.000000      6
2.000000       2
22.739574      1
16.486762      1
31.098236      1
27.659572      1
22.453227      1
27.161573      1
24.444454      1
29.165370      1
27.829321      1
28.778165      1
12.822720      1
28.341413      1
30.461302      1
33.352217      1
33.048958      1
Name: count, dtype: int64

In [10]:
df['Days_Without_Social_Media'].value_counts()

Days_Without_Social_Media
3.000000     84
2.000000     79
4.000000     75
5.000000     72
1.000000     53
0.000000     45
6.000000     35
7.000000     14
11.831561     1
15.545850     1
14.922192     1
11.092814     1
12.114073     1
8.473052      1
12.291890     1
9.626726      1
7.528696      1
14.642574     1
9.923745      1
12.616104     1
12.506984     1
8.608089      1
7.126193      1
11.265042     1
10.781575     1
12.706946     1
9.291501      1
8.994814      1
7.405099      1
12.902618     1
9.000000      1
11.238624     1
10.993299     1
10.026054     1
Name: count, dtype: int64

In [11]:
df['Exercise_Frequency(week)'].value_counts()

Exercise_Frequency(week)
2.000000     119
3.000000     109
1.000000      85
4.000000      68
0.000000      41
5.000000      34
6.000000       4
5.622212       1
9.059902       1
11.809694      1
6.449423       1
9.443727       1
6.817550       1
9.011844       1
6.459707       1
10.478078      1
9.583536       1
7.923380       1
8.816807       1
7.275924       1
7.936498       1
7.063421       1
5.573589       1
7.878397       1
11.345462      1
5.616623       1
5.766829       1
10.030890      1
11.946164      1
7.000000       1
5.265107       1
Name: count, dtype: int64

In [12]:
df['Social_Media_Platform'].value_counts()

Social_Media_Platform
TikTok         83
X (Twitter)    83
LinkedIn       80
Facebook       76
Instagram      73
YouTube        68
ERR            37
Name: count, dtype: int64

In [14]:
df['Happiness_Index(1-10)'].value_counts()

Happiness_Index(1-10)
10.000000    148
8.000000     100
9.000000      85
7.000000      69
6.000000      34
5.000000      14
4.000000       6
23.012565      1
40.554534      1
40.456189      1
36.540281      1
22.383707      1
23.519798      1
19.532661      1
24.253221      1
34.417287      1
41.477006      1
32.899530      1
30.051538      1
27.671882      1
27.457855      1
40.359127      1
23.034413      1
38.928872      1
Name: count, dtype: int64

In [15]:
df['Age'].value_counts()

Age
43.000000     21
48.000000     21
47.000000     20
41.000000     20
39.000000     18
31.000000     18
17.000000     17
27.000000     17
23.000000     17
34.000000     16
40.000000     16
38.000000     16
18.000000     15
37.000000     14
44.000000     14
16.000000     13
22.000000     13
32.000000     12
45.000000     12
26.000000     12
20.000000     12
36.000000     12
35.000000     12
19.000000     11
42.000000     11
21.000000     11
29.000000     10
30.000000     10
24.000000     10
33.000000      9
46.000000      9
28.000000      8
49.000000      8
25.000000      7
141.420044     1
128.962066     1
165.103665     1
162.462624     1
134.557153     1
159.561241     1
150.425237     1
142.056241     1
127.109131     1
158.042641     1
132.406668     1
112.414514     1
89.538699      1
111.330877     1
115.574836     1
70.411879      1
123.946695     1
180.626294     1
120.099969     1
93.023903      1
Name: count, dtype: int64

In [4]:
df["duplikaty"]=df.duplicated(keep="first")
df

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10),duplikaty
0,U001,NaN,ERR,3.1,7.0,NaN,2.0,5.000000,Facebook,10.0,False
1,U002,30.0,Other,5.1,7.0,8.0,5.0,3.000000,LinkedIn,10.0,False
2,U003,23.0,ERR,7.4,6.0,NaN,1.0,5.622212,YouTube,6.0,False
3,U004,36.0,Female,5.7,7.0,8.0,1.0,1.000000,TikTok,8.0,False
4,U005,34.0,Female,7.0,4.0,7.0,5.0,1.000000,X (Twitter),8.0,False
...,...,...,...,...,...,...,...,...,...,...,...
495,ERR,23.0,ERR,6.9,5.0,7.0,4.0,2.000000,ERR,10.0,False
496,U497,43.0,Female,5.6,7.0,6.0,5.0,2.000000,Facebook,9.0,False
497,U498,41.0,Male,7.7,5.0,NaN,2.0,5.265107,ERR,8.0,False
498,U499,23.0,Male,4.2,9.0,7.0,0.0,2.000000,Facebook,9.0,False
499,U500,43.0,Female,5.9,5.0,8.0,3.0,3.000000,X (Twitter),7.0,False

In [14]:
dfQ = df.copy()

dfQ['User_ID'] = ['U' + str(i+1).zfill(3) for i in range(len(dfQ))]
dfQ.loc[dfQ['Age'] > 110, 'Age'] = pd.NA
dfQ['Gender'] = df['Gender'].replace('ERR', pd.NA)
dfQ.loc[dfQ['Daily_Screen_Time(hrs)'] > 11, 'Daily_Screen_Time(hrs)'] = pd.NA
dfQ.loc[dfQ['Sleep_Quality(1-10)'] > 10, 'Sleep_Quality(1-10)'] = pd.NA
dfQ.loc[dfQ['Stress_Level(1-10)'] > 10, 'Stress_Level(1-10)'] = pd.NA
dfQ.loc[dfQ['Days_Without_Social_Media'] > 7, 'Days_Without_Social_Media'] = pd.NA
#Exercise_Frequency(week)  dfQ.loc[dfQ['Exercise_Frequency(week)'] > 7, 'Exercise_Frequency(week)'] = pd.NA
dfQ = dfQ[dfQ['Social_Media_Platform'] != 'ERR']
dfQ.loc[dfQ['Happiness_Index(1-10)'] > 10, 'Happiness_Index(1-10)'] = pd.NA

dfQ

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,NaN,<NA>,3.1,7.0,NaN,2.0,5.000000,Facebook,10.0
1,U002,30.0,Other,5.1,7.0,8.0,5.0,3.000000,LinkedIn,10.0
2,U003,23.0,<NA>,7.4,6.0,NaN,1.0,5.622212,YouTube,6.0
3,U004,36.0,Female,5.7,7.0,8.0,1.0,1.000000,TikTok,8.0
4,U005,34.0,Female,7.0,4.0,7.0,5.0,1.000000,X (Twitter),8.0
...,...,...,...,...,...,...,...,...,...,...
493,U494,39.0,Female,3.0,7.0,2.0,1.0,0.000000,Facebook,10.0
494,U495,43.0,Female,5.6,8.0,NaN,NaN,0.000000,Instagram,10.0
496,U497,43.0,Female,5.6,7.0,6.0,5.0,2.000000,Facebook,9.0
498,U499,23.0,Male,4.2,9.0,7.0,0.0,2.000000,Facebook,9.0
499,U500,43.0,Female,5.9,5.0,8.0,3.0,3.000000,X (Twitter),7.0

In [20]:
dfQ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    500 non-null    object
 1   Age                        482 non-null    float64
 2   Gender                     475 non-null    object
 3   Daily_Screen_Time(hrs)     465 non-null    float64
 4   Sleep_Quality(1-10)        475 non-null    Int64
 5   Stress_Level(1-10)         457 non-null    Int64
 6   Days_Without_Social_Media  483 non-null    float64
 7   Exercise_Frequency(week)   484 non-null    Int64
 8   Social_Media_Platform      463 non-null    object
 9   Happiness_Index(1-10)      456 non-null    Int64
dtypes: Int64(4), float64(3), object(3)
memory usage: 41.1+ KB

In [15]:
dfQ['Age'] = np.ceil(dfQ['Age']).astype('Int64')
dfQ['Sleep_Quality(1-10)']=dfQ['Sleep_Quality(1-10)'].astype('Int64')
dfQ['Stress_Level(1-10)']=dfQ['Stress_Level(1-10)'].astype('Int64')
dfQ['Days_Without_Social_Media']=dfQ['Days_Without_Social_Media'].astype('Int64')
dfQ['Exercise_Frequency(week)'] = np.ceil(dfQ['Exercise_Frequency(week)']).astype('Int64')
dfQ['Happiness_Index(1-10)']=dfQ['Happiness_Index(1-10)'].astype('Int64')
dfQ

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,<NA>,<NA>,3.1,7,<NA>,2,5,Facebook,10
1,U002,30,Other,5.1,7,8,5,3,LinkedIn,10
2,U003,23,<NA>,7.4,6,<NA>,1,6,YouTube,6
3,U004,36,Female,5.7,7,8,1,1,TikTok,8
4,U005,34,Female,7.0,4,7,5,1,X (Twitter),8
...,...,...,...,...,...,...,...,...,...,...
493,U494,39,Female,3.0,7,2,1,0,Facebook,10
494,U495,43,Female,5.6,8,<NA>,<NA>,0,Instagram,10
496,U497,43,Female,5.6,7,6,5,2,Facebook,9
498,U499,23,Male,4.2,9,7,0,2,Facebook,9
499,U500,43,Female,5.9,5,8,3,3,X (Twitter),7

In [11]:
'''dfQ['User_ID'] = ['U' + str(i+1).zfill(3) for i in range(len(dfQ))]
dfQ.head(10)'''

,User_ID,Age,Gender,Daily_Screen_Time(hrs),Sleep_Quality(1-10),Stress_Level(1-10),Days_Without_Social_Media,Exercise_Frequency(week),Social_Media_Platform,Happiness_Index(1-10)
0,U001,<NA>,<NA>,3.1,7,<NA>,2,5,Facebook,10
1,U002,30,Other,5.1,7,8,5,3,LinkedIn,10
2,U003,23,<NA>,7.4,6,<NA>,1,6,YouTube,6
3,U004,36,Female,5.7,7,8,1,1,TikTok,8
4,U005,34,Female,7.0,4,7,5,1,X (Twitter),8
5,U006,38,Male,6.6,5,7,4,3,LinkedIn,8
6,U007,26,Female,7.8,4,8,2,0,TikTok,7
7,U008,26,Female,7.4,5,6,1,4,Instagram,7
8,U009,39,Male,4.7,7,7,6,1,YouTube,9
9,U010,<NA>,<NA>,6.6,6,8,0,2,Facebook,<NA>

In [12]:
dfQ.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    500 non-null    object
 1   Age                        465 non-null    Int64
 2   Gender                     475 non-null    object
 3   Daily_Screen_Time(hrs)     465 non-null    float64
 4   Sleep_Quality(1-10)        475 non-null    Int64
 5   Stress_Level(1-10)         457 non-null    Int64
 6   Days_Without_Social_Media  457 non-null    Int64
 7   Exercise_Frequency(week)   484 non-null    Int64
 8   Social_Media_Platform      463 non-null    object
 9   Happiness_Index(1-10)      456 non-null    Int64
dtypes: Int64(6), float64(1), object(3)
memory usage: 42.1+ KB

In [17]:
dfQ['Daily_Screen_Time(hrs)'].nlargest(20)

248    10.8
325    10.8
202    10.0
212     9.8
76      9.7
388     9.7
440     9.5
241     9.4
263     9.1
337     9.1
479     9.0
230     8.8
412     8.8
436     8.8
215     8.7
265     8.7
481     8.6
165     8.5
59      8.4
347     8.4
Name: Daily_Screen_Time(hrs), dtype: float64

In [16]:
dfQ.to_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_clean.csv")

In [23]:
dfQ1 =dfQ.dropna(subset=["Daily_Screen_Time(hrs)", "Happiness_Index(1-10)"], thresh=2)
dfQ1 = dfQ1 [['User_ID', 'Daily_Screen_Time(hrs)', 'Happiness_Index(1-10)', 'Social_Media_Platform']]
dfQ1

,User_ID,Daily_Screen_Time(hrs),Happiness_Index(1-10),Social_Media_Platform
0,U001,3.1,10,Facebook
1,U002,5.1,10,LinkedIn
2,U003,7.4,6,YouTube
3,U004,5.7,8,TikTok
4,U005,7.0,8,X (Twitter)
...,...,...,...,...
493,U494,3.0,10,Facebook
494,U495,5.6,10,Instagram
496,U497,5.6,9,Facebook
498,U499,4.2,9,Facebook
499,U500,5.9,7,X (Twitter)

In [24]:
dfQ2= dfQ.dropna(subset=["Exercise_Frequency(week)", "Sleep_Quality(1-10)","Stress_Level(1-10)"], thresh=3)
dfQ2 = dfQ2 [['User_ID', 'Exercise_Frequency(week)', 'Sleep_Quality(1-10)', 'Stress_Level(1-10)', 'Social_Media_Platform']]
dfQ2

,User_ID,Exercise_Frequency(week),Sleep_Quality(1-10),Stress_Level(1-10),Social_Media_Platform
1,U002,3,7,8,LinkedIn
3,U004,1,7,8,TikTok
4,U005,1,4,7,X (Twitter)
5,U006,3,5,7,LinkedIn
6,U007,0,4,8,TikTok
...,...,...,...,...,...
492,U493,5,5,7,Facebook
493,U494,0,7,2,Facebook
496,U497,2,7,6,Facebook
498,U499,2,9,7,Facebook
499,U500,3,5,8,X (Twitter)

In [25]:
dfQ3 = dfQ.dropna(subset=["Days_Without_Social_Media", "Happiness_Index(1-10)"], thresh=2)
dfQ3 = dfQ3 [['User_ID', 'Days_Without_Social_Media', 'Happiness_Index(1-10)', 'Social_Media_Platform']]
dfQ3

,User_ID,Days_Without_Social_Media,Happiness_Index(1-10),Social_Media_Platform
0,U001,2,10,Facebook
1,U002,5,10,LinkedIn
2,U003,1,6,YouTube
3,U004,1,8,TikTok
4,U005,5,8,X (Twitter)
...,...,...,...,...
492,U493,6,9,Facebook
493,U494,1,10,Facebook
496,U497,5,9,Facebook
498,U499,0,9,Facebook
499,U500,3,7,X (Twitter)

In [26]:
dfQ4 = dfQ.dropna(subset=["Age", "Gender", "Social_Media_Platform", "Happiness_Index(1-10)"], thresh=4)
dfQ4 = dfQ4 [['User_ID', 'Age', 'Gender', 'Social_Media_Platform', 'Happiness_Index(1-10)']]
dfQ4

    User_ID  Age  Gender Social_Media_Platform  Happiness_Index(1-10)
1      U002   30   Other              LinkedIn                     10
3      U004   36  Female                TikTok                      8
4      U005   34  Female           X (Twitter)                      8
5      U006   38    Male              LinkedIn                      8
6      U007   26  Female                TikTok                      7
..      ...  ...     ...                   ...                    ...
493    U494   39  Female              Facebook                     10
494    U495   43  Female             Instagram                     10
496    U497   43  Female              Facebook                      9
498    U499   23    Male              Facebook                      9
499    U500   43  Female           X (Twitter)                      7

[391 rows x 5 columns]

In [27]:
dfQ1.to_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_clean_Q1.csv")
dfQ2.to_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_clean_Q2.csv")
dfQ3.to_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_clean_Q3.csv")
dfQ4.to_csv(r"C:\Users\karolina.koziol\Documents\studia\praca-dyplomowa\Mental_Health_and_Social_Media_Balance_Dataset_clean_Q4.csv")